name: Feature Proposal
description: Propose a new feature/change for the game
labels: ["Type: Change/Feature Request", "NEW ISSUE"] 
body:
- type: markdown
  attributes:
    value: |
      ## Is there an existing suggestion for this?
      Please search to see if an issue already exists for the feature you wish to propose.
- type: dropdown
  id: contribute
  attributes:
    label: Do you intend to personally contribute/program this feature?
    description: If you feel confident that you can contribute this feature, feel free to work on it after getting some initial feedback. If you can't, don't worry, there are many people who can help and the suggestion is great by itself.
    multiple: false
    options:
      - 'Yes'
      - 'No'
  validations:
    required: true   
- type: textarea
  id: description
  attributes:
    label: Description
    description: |
      Describe your proposal. 
    placeholder: |
      A new scene called CoolScene could allow modders to...
- type: textarea
  id: why
  attributes:
    label: What does this proposal attempt to solve or improve?
    description: |
      Describe how your proposal is beneficial for the the game. Please list an example use case for the new feature.
    placeholder: |
      It is currently impossible to have the Player...
      This new feature would allow us to implement...
- type: textarea
  id: alternatives
  attributes:
    label: Which (other) solutions should be considered?
    description: |
      Are there alternatives to your proposal? Please list them here. It is okay to leave this empty if none are applicable.
